### ISSUE TITLE
slice bounds out of range in push hook handling

### ISSUE THREAD

**Issue by mweinelt** [f-breidenstein/go-gitlab-irc#12]
Pushes are posted repeatedly to IRC, Gitlab probably retries pushing this, because of a non 200 HTTP response on the API.

```
go-gitlab-irc[31119]: 2017/08/07 00:13:25 http: panic serving 127.0.0.1:48084: runtime error: slice bounds out of range
go-gitlab-irc[31119]: goroutine 53 [running]:
go-gitlab-irc[31119]: net/http.(*conn).serve.func1(0xc420082000)
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
go-gitlab-irc[31119]: panic(0x7802c0, 0x99e570)
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
go-gitlab-irc[31119]: main.CreateFunctionNotifyFunction.func1(0x97aae0, 0xc42008e000, 0xc420136c00)
go-gitlab-irc[31119]:         /usr/local/go/src/github.com/f-breidenstein/go-gitlab-irc/main.go:197 +0xfc9
go-gitlab-irc[31119]: net/http.HandlerFunc.ServeHTTP(0xc420417e50, 0x97aae0, 0xc42008e000, 0xc420136c00)
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/net/http/server.go:1942 +0x44
go-gitlab-irc[31119]: net/http.(*ServeMux).ServeHTTP(0x9aba20, 0x97aae0, 0xc42008e000, 0xc420136c00)
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/net/http/server.go:2238 +0x130
go-gitlab-irc[31119]: net/http.serverHandler.ServeHTTP(0xc4204258c0, 0x97aae0, 0xc42008e000, 0xc420136c00)
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
go-gitlab-irc[31119]: net/http.(*conn).serve(0xc420082000, 0x97b1a0, 0xc420050140)
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
go-gitlab-irc[31119]: created by net/http.(*Server).Serve
go-gitlab-irc[31119]:         /usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
```

**Comment by mweinelt** [comment]
https://github.com/f-breidenstein/go-gitlab-irc/commit/7a8969ff35d9d571b4063e909a64acac58a7531b

should probably take care of that.
