### ISSUE TITLE
http: panic serving [::1]:34550: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by mweinelt** [f-breidenstein/go-gitlab-irc#24]
Saw the following issue after two merges and the bot keeps repeating the push messages saying $ALL commits were pushed to $BRANCH.

```
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: 2018/08/22 20:37:51 Got Hook for a Push Event
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: 2018/08/22 20:37:51 http: panic serving [::1]:34550: runtime error: slice bounds out of range
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: goroutine 805 [running]:
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: net/http.(*conn).serve.func1(0xc420097040)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/net/http/server.go:1721 +0xd0
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: panic(0x784660, 0x9a4570)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: main.CreateFunctionNotifyFunction.func1(0x980ae0, 0xc4200aa000, 0xc4200a0600)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/local/go/src/github.com/f-breidenstein/go-gitlab-irc/main.go:354 +0xb4e
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: net/http.HandlerFunc.ServeHTTP(0xc4204f6a00, 0x980ae0, 0xc4200aa000, 0xc4200a0600)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/net/http/server.go:1942 +0x44
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: net/http.(*ServeMux).ServeHTTP(0x9b1a20, 0x980ae0, 0xc4200aa000, 0xc4200a0600)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/net/http/server.go:2238 +0x130
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: net/http.serverHandler.ServeHTTP(0xc4204fc000, 0x980ae0, 0xc4200aa000, 0xc4200a0600)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/net/http/server.go:2568 +0x92
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: net/http.(*conn).serve(0xc420097040, 0x9811a0, 0xc420080280)
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/net/http/server.go:1825 +0x612
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]: created by net/http.(*Server).Serve
Aug 22 20:37:51 git.darmstadt.ccc.de go-gitlab-irc[514]:         /usr/lib/go-1.8/src/net/http/server.go:2668 +0x2ce
```

**Comment by fleaz** [comment]
This was probably also related to the Gitlab 11.2 bug or did it appear again after updating our GitLab instance? Feel free to close this.
